#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 19 03:18:13 2020

@author: joedattoli
"""

import pandas as pd
from scipy.optimize import linprog

batter_frame = pd.read_csv(r'/Users/joedattoli/Desktop/CSVFILES/full_batter_frame.csv')


war = list(batter_frame['WAR'].values)
z_war = [-1 * i for i in war]

salary =  list(batter_frame['salary'].values)
c = list(batter_frame['C'].values)
c_i = [-1*i for i in c]
first_base = list(batter_frame['B1'].values)
second_base = list(batter_frame['B2'].values)
third_base = list(batter_frame['B3'].values)
shortstop = list(batter_frame['SS'].values)
leftfield = list(batter_frame['LF'].values)
centerfield = list(batter_frame['CF'].values)
rightfield = list(batter_frame['RF'].values)
dh = list(batter_frame['DH'].values)



of = [1 if ((leftfield[i] == 1 or centerfield == 1 or rightfield == 1) )else 0 for i in range(len(batter_frame.index)) ]
inf = [1 if (first_base[i]== 1 or second_base[i]==1 or third_base[i] == 1 or shortstop[i]== 1) else 0 for i in range(len(batter_frame.index))  ]
roster_size = [1 for i in range(len(batter_frame.index))]
roster_size_ = [-1 for i in range(len(batter_frame.index))]

A = [salary, c_i, of, inf, roster_size]

b = [100000000, 2, 5, 6, 13]

result = linprog(z_war,A,b, bounds = [(0,1) for i in range(len(batter_frame.index))], method = 'revised simplex')

x = result.x
print(sum(x))
for i in range(len(x)):
    if x[i] > 0:
        print(batter_frame['Name'][i] , batter_frame['WAR'][i], batter_frame['salary'][i] )
print(-1*round(result.fun,1))

